CREATE TYPE "UserRole" AS ENUM ('ADMIN');
CREATE TYPE "ProductAudience" AS ENUM ('SCHOOL', 'CORPORATE', 'INSTITUTION', 'GENERAL');
CREATE TYPE "ProductStockStatus" AS ENUM ('IN_STOCK', 'LOW_STOCK', 'OUT_OF_STOCK', 'MADE_TO_ORDER');
CREATE TYPE "FulfilmentType" AS ENUM ('READY_STOCK', 'MADE_TO_ORDER', 'CUSTOMIZED');
CREATE TYPE "AssetType" AS ENUM ('LOGO', 'CATALOGUE', 'PRODUCT_IMAGE', 'SOCIAL_IMAGE', 'OTHER');

CREATE TABLE "User" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "email" TEXT NOT NULL, "passwordHash" TEXT NOT NULL, "role" "UserRole" NOT NULL DEFAULT 'ADMIN', "active" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Category" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "slug" TEXT NOT NULL, "description" TEXT, "imageUrl" TEXT, "active" BOOLEAN NOT NULL DEFAULT true, "sortOrder" INTEGER NOT NULL DEFAULT 0, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Category_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Product" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "slug" TEXT NOT NULL, "sku" TEXT NOT NULL, "shortDescription" TEXT NOT NULL, "description" TEXT NOT NULL, "categoryId" TEXT NOT NULL, "subcategory" TEXT, "audience" "ProductAudience" NOT NULL, "institutionName" TEXT, "schoolName" TEXT, "brand" TEXT, "price" DECIMAL(12,2), "offerPrice" DECIMAL(12,2), "gstPercentage" DECIMAL(5,2) NOT NULL DEFAULT 18, "minimumOrderQuantity" INTEGER NOT NULL DEFAULT 1, "stockQuantity" INTEGER NOT NULL DEFAULT 0, "stockStatus" "ProductStockStatus" NOT NULL DEFAULT 'IN_STOCK', "material" TEXT, "sizes" JSONB NOT NULL, "colours" JSONB NOT NULL, "weight" TEXT, "deliveryTime" TEXT NOT NULL, "fulfilmentType" "FulfilmentType" NOT NULL DEFAULT 'READY_STOCK', "customizationAvailable" BOOLEAN NOT NULL DEFAULT false, "embroideryAvailable" BOOLEAN NOT NULL DEFAULT false, "printingAvailable" BOOLEAN NOT NULL DEFAULT false, "featured" BOOLEAN NOT NULL DEFAULT false, "published" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Product_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ProductImage" ("id" TEXT NOT NULL, "productId" TEXT NOT NULL, "url" TEXT NOT NULL, "pathname" TEXT, "altText" TEXT NOT NULL, "isPrimary" BOOLEAN NOT NULL DEFAULT false, "sortOrder" INTEGER NOT NULL DEFAULT 0, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "ProductImage_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SiteAsset" ("id" TEXT NOT NULL, "type" "AssetType" NOT NULL, "title" TEXT NOT NULL, "url" TEXT NOT NULL, "pathname" TEXT, "mimeType" TEXT, "fileSize" INTEGER, "active" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "SiteAsset_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SiteSetting" ("id" TEXT NOT NULL, "key" TEXT NOT NULL, "value" JSONB NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "SiteSetting_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AdminAuditLog" ("id" TEXT NOT NULL, "userId" TEXT, "action" TEXT NOT NULL, "entityType" TEXT NOT NULL, "entityId" TEXT, "details" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AdminAuditLog_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "User_email_key" ON "User"("email"); CREATE INDEX "User_active_role_idx" ON "User"("active", "role");
CREATE UNIQUE INDEX "Category_slug_key" ON "Category"("slug"); CREATE INDEX "Category_active_sortOrder_idx" ON "Category"("active", "sortOrder");
CREATE UNIQUE INDEX "Product_slug_key" ON "Product"("slug"); CREATE UNIQUE INDEX "Product_sku_key" ON "Product"("sku"); CREATE INDEX "Product_categoryId_published_idx" ON "Product"("categoryId", "published"); CREATE INDEX "Product_audience_stockStatus_idx" ON "Product"("audience", "stockStatus"); CREATE INDEX "Product_featured_published_idx" ON "Product"("featured", "published"); CREATE INDEX "Product_updatedAt_idx" ON "Product"("updatedAt");
CREATE INDEX "ProductImage_productId_isPrimary_sortOrder_idx" ON "ProductImage"("productId", "isPrimary", "sortOrder"); CREATE INDEX "SiteAsset_type_active_updatedAt_idx" ON "SiteAsset"("type", "active", "updatedAt"); CREATE UNIQUE INDEX "SiteSetting_key_key" ON "SiteSetting"("key"); CREATE INDEX "AdminAuditLog_userId_createdAt_idx" ON "AdminAuditLog"("userId", "createdAt"); CREATE INDEX "AdminAuditLog_entityType_entityId_createdAt_idx" ON "AdminAuditLog"("entityType", "entityId", "createdAt");

ALTER TABLE "Product" ADD CONSTRAINT "Product_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "Category"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ProductImage" ADD CONSTRAINT "ProductImage_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AdminAuditLog" ADD CONSTRAINT "AdminAuditLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
