export type ProductAudience = "SCHOOL" | "CORPORATE" | "INSTITUTION" | "GENERAL";
export type StockStatus = "IN_STOCK" | "LOW_STOCK" | "OUT_OF_STOCK" | "MADE_TO_ORDER";

export type Product = {
  id: string;
  slug: string;
  name: string;
  sku: string;
  shortDescription: string;
  description: string;
  category: string;
  subcategory: string;
  audience: ProductAudience;
  institutionName?: string;
  schoolName?: string;
  brand: string;
  price: number | null;
  offerPrice?: number;
  gstPercentage: number;
  minimumOrderQuantity: number;
  stockQuantity: number;
  stockStatus: StockStatus;
  material: string;
  sizes: string[];
  colours: string[];
  weight?: string;
  deliveryTime: string;
  customizationAvailable: boolean;
  embroideryAvailable: boolean;
  printingAvailable: boolean;
  featured: boolean;
  published: boolean;
  createdAt: string;
  mainImage: string;
  galleryImages: string[];
  features: string[];
  specifications: Record<string, string>;
  tags: string[];
};
