import type { Metadata } from "next";
import Link from "next/link";
import { Award, BadgeCheck, BriefcaseBusiness, Building2, GraduationCap, MessageCircle, PackageCheck, Palette, ShieldCheck, Shirt, Sparkles, Trophy } from "lucide-react";
import ProductCard from "@/components/ProductCard";
import { categories, products } from "@/data/products";
import DownloadCatalogueButton from "@/components/DownloadCatalogueButton";

export const metadata: Metadata = { title: "Premium Uniforms & Customized Products", description: "DS CREATIONS manufactures uniforms, awards, apparel, stationery and customized products for schools and businesses." };
const categoryIcons = [Shirt, BriefcaseBusiness, Trophy, Sparkles, PackageCheck, Award];
export default function HomePage() { const featured = products.filter((p) => p.featured).slice(0, 4); return <>
  <section className="blue-gradient overflow-hidden text-white"><div className="container-custom grid min-h-[670px] items-center gap-12 py-20 lg:grid-cols-[1.1fr_.9fr]"><div><p className="eyebrow">Direct Manufacturer · New Delhi</p><h1 className="mt-5 max-w-4xl text-4xl font-black leading-tight sm:text-5xl lg:text-6xl">Premium Uniforms and Customized Products for Schools and Businesses</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/80">DS CREATIONS manufactures school uniforms, corporate apparel, trophies, medals, diaries, ID cards, steel flasks and customized institutional products.</p><div className="mt-9 grid max-w-2xl gap-3 sm:grid-cols-2"><Link href="/products" className="btn-gold text-center">EXPLORE PRODUCTS</Link><DownloadCatalogueButton className="btn-secondary w-full border-white/30 bg-transparent text-white hover:text-[var(--dark-navy)]" showMessage /><Link href="/bulk-orders" className="btn-secondary border-white/30 bg-transparent text-center text-white hover:text-[var(--dark-navy)]">REQUEST A QUOTE</Link><a href="https://wa.me/918368045535" target="_blank" rel="noreferrer" className="btn-gold flex items-center justify-center gap-2"><MessageCircle size={18} />WHATSAPP US</a></div></div><div className="relative"><div className="absolute -inset-6 rounded-full bg-[var(--gold)]/20 blur-3xl" /><div className="relative rounded-[32px] border border-white/15 bg-white/10 p-7 backdrop-blur"><div className="grid grid-cols-2 gap-4">{[[Shirt,"Uniforms"],[Trophy,"Awards"],[Palette,"Customization"],[PackageCheck,"Bulk Supply"]].map(([Icon,label]) => { const I = Icon as typeof Shirt; return <div key={label as string} className="rounded-2xl bg-white p-6 text-center text-[var(--dark-navy)]"><I className="mx-auto text-[var(--royal-blue)]" size={36} /><p className="mt-3 font-black">{label as string}</p></div>;})}</div><div className="mt-4 rounded-2xl bg-[var(--gold)] p-6 text-[var(--dark-navy)]"><p className="text-sm font-bold uppercase tracking-[.2em]">Our focus</p><p className="mt-2 text-2xl font-black">Quality · Customization · Dependable Supply</p></div></div></div></div></section>
  <section className="section-space bg-[var(--light-bg)]"><div className="container-custom"><p className="eyebrow !text-[var(--royal-blue)]">Product Categories</p><h2 className="mt-3 text-3xl font-black text-[var(--dark-navy)] sm:text-4xl">Complete institutional supply solutions</h2><div className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{categories.slice(0,6).map((category,index) => { const I = categoryIcons[index]; return <Link href={`/products`} key={category} className="content-card flex items-center gap-5 p-6 hover:-translate-y-1 hover:border-[var(--gold)]"><span className="rounded-xl bg-[var(--royal-blue)] p-3 text-[var(--gold)]"><I /></span><span><strong className="block text-lg text-[var(--dark-navy)]">{category}</strong><span className="text-sm text-slate-500">Explore products</span></span></Link>;})}</div></div></section>
  <section className="section-space bg-white"><div className="container-custom"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow !text-[var(--royal-blue)]">Featured Products</p><h2 className="mt-3 text-3xl font-black text-[var(--dark-navy)]">Popular starting points</h2></div><Link href="/products" className="btn-secondary">View all products</Link></div><div className="mt-9 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{featured.map((product) => <ProductCard key={product.id} product={product} />)}</div></div></section>
  <section className="section-space bg-[var(--dark-navy)] text-white"><div className="container-custom"><div className="text-center"><p className="eyebrow">Solutions by Audience</p><h2 className="mt-3 text-3xl font-black sm:text-4xl">Designed around how your organization works</h2></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{[[GraduationCap,"Schools","Uniforms, identity products, bags and stationery.","SCHOOL"],[BriefcaseBusiness,"Corporate","Professional apparel, gifts and branded products.","CORPORATE"],[Building2,"Institutions","Coordinated staff wear, awards and supplies.","INSTITUTION"],[Trophy,"Events & General","Apparel, caps, medals, trophies and merchandise.","GENERAL"]].map(([Icon,title,text,audience]) => { const I = Icon as typeof Trophy; return <Link href={`/products?audience=${audience}`} key={title as string} className="rounded-2xl border border-white/15 bg-white/5 p-6 hover:border-[var(--gold)]"><I className="text-[var(--gold)]" size={30} /><h3 className="mt-5 text-xl font-black">{title as string}</h3><p className="mt-3 leading-7 text-white/65">{text as string}</p></Link>;})}</div></div></section>
  <section className="section-space bg-white"><div className="container-custom"><p className="eyebrow !text-[var(--royal-blue)]">Why Choose DS CREATIONS</p><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{[[BadgeCheck,"Manufacturing Focus","Products built around the intended use."],[Palette,"Customization","Colours, logos, printing and embroidery."],[PackageCheck,"Bulk Expertise","Structured support for volume requirements."],[ShieldCheck,"Quality Checks","Specifications reviewed before dispatch."]].map(([Icon,title,text]) => { const I=Icon as typeof BadgeCheck; return <div key={title as string} className="content-card p-6"><I className="text-[var(--dark-gold)]" /><h3 className="mt-4 text-xl font-black text-[var(--dark-navy)]">{title as string}</h3><p className="mt-2 text-slate-600">{text as string}</p></div>;})}</div></div></section>
  <section className="section-space bg-[var(--soft-gold)]"><div className="container-custom"><p className="eyebrow !text-[var(--royal-blue)]">Customization Process</p><div className="mt-8 grid gap-5 md:grid-cols-4">{["Share your requirement","Confirm materials & branding","Approve specifications","Production & delivery coordination"].map((step,index) => <div key={step} className="rounded-2xl bg-white p-6"><span className="text-3xl font-black text-[var(--gold)]">0{index+1}</span><h3 className="mt-3 font-black text-[var(--dark-navy)]">{step}</h3></div>)}</div></div></section>
  <section className="section-space bg-white"><div className="container-custom rounded-[32px] bg-[var(--royal-blue)] p-8 text-white sm:p-12 lg:flex lg:items-center lg:justify-between"><div><p className="eyebrow">Schools · Companies · Institutions</p><h2 className="mt-3 max-w-3xl text-3xl font-black">Planning a bulk order or need a tailored recommendation?</h2><p className="mt-3 text-white/70">Talk with DS CREATIONS about products, quantities, sizes and branding.</p></div><div className="mt-7 flex flex-wrap gap-3 lg:mt-0"><Link href="/industries" className="btn-secondary">Industries We Serve</Link><Link href="/bulk-orders" className="btn-gold">Request a Quote</Link><Link href="/contact" className="btn-secondary">Contact Us</Link></div></div></section>
  </>; }
