import type { Metadata } from "next";
import Link from "next/link";
import { BadgeCheck, BriefcaseBusiness, Building2, GraduationCap, MessageCircle, PackageCheck, Palette, ShieldCheck, Shirt, Trophy } from "lucide-react";
import ProductCard from "@/components/ProductCard";
import DownloadCatalogueButton from "@/components/DownloadCatalogueButton";
import { getPublicProducts } from "@/lib/product-data";
import { getPublicSettings } from "@/lib/site-data";
import { getActiveCatalogue } from "@/lib/site-assets";

export const metadata: Metadata = { title: "Premium Uniforms & Customized Products", description: "DS CREATIONS manufactures uniforms, awards, apparel, stationery and customized products for schools and businesses." };
const categoryIcons = [Shirt, BriefcaseBusiness, Trophy, Palette, PackageCheck, ShieldCheck];

export default async function HomePage() {
  const [products, settings, catalogue] = await Promise.all([getPublicProducts(), getPublicSettings(), getActiveCatalogue()]);
  const categories = [...new Set(products.map((product) => product.category))].sort();
  const featured = products.filter((product) => product.featured).slice(0, 4);
  return <>
    <section className="blue-gradient overflow-hidden text-white"><div className="container-custom grid min-h-[650px] items-center gap-12 py-20 lg:grid-cols-[1.1fr_.9fr]"><div><p className="eyebrow">Direct Manufacturer · New Delhi</p><h1 className="mt-5 max-w-4xl text-4xl font-black leading-tight sm:text-5xl lg:text-6xl">{String(settings.heroHeading)}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/80">{String(settings.heroSupportingText)}</p><div className="mt-9 grid max-w-2xl gap-3 sm:grid-cols-2"><Link href="/products" className="btn-gold text-center">EXPLORE PRODUCTS</Link><DownloadCatalogueButton catalogue={catalogue} className="btn-secondary w-full border-white/30 bg-transparent text-white hover:text-[var(--dark-navy)]" showMessage /><Link href="/bulk-orders" className="btn-secondary border-white/30 bg-transparent text-center text-white hover:text-[var(--dark-navy)]">REQUEST A QUOTE</Link><a href={`https://wa.me/${String(settings.whatsapp)}`} target="_blank" rel="noreferrer" className="btn-gold flex items-center justify-center gap-2"><MessageCircle size={18} />WHATSAPP US</a></div></div><div className="grid grid-cols-2 gap-4">{[[Shirt, "Uniforms"], [Trophy, "Awards"], [Palette, "Customization"], [PackageCheck, "Optional Bulk Supply"]].map(([Icon, label]) => { const I = Icon as typeof Shirt; return <div key={label as string} className="rounded-2xl bg-white p-6 text-center text-[var(--dark-navy)]"><I className="mx-auto text-[var(--royal-blue)]" size={36} /><p className="mt-3 font-black">{label as string}</p></div>; })}</div></div></section>
    <section className="section-space bg-[var(--light-bg)]"><div className="container-custom"><p className="eyebrow !text-[var(--royal-blue)]">Product Categories</p><h2 className="mt-3 text-3xl font-black text-[var(--dark-navy)]">Complete institutional supply solutions</h2><div className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{categories.slice(0, 6).map((category, index) => { const I = categoryIcons[index]; return <Link href="/products" key={category} className="content-card flex items-center gap-5 p-6 hover:border-[var(--gold)]"><span className="rounded-xl bg-[var(--royal-blue)] p-3 text-[var(--gold)]"><I /></span><strong className="text-lg text-[var(--dark-navy)]">{category}</strong></Link>; })}</div></div></section>
    <section className="section-space bg-white"><div className="container-custom"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow !text-[var(--royal-blue)]">Featured Products</p><h2 className="mt-3 text-3xl font-black text-[var(--dark-navy)]">Popular starting points</h2></div><Link href="/products" className="btn-secondary">View all products</Link></div><div className="mt-9 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{featured.map((product) => <ProductCard key={product.id} product={product} />)}</div></div></section>
    <section className="section-space bg-[var(--dark-navy)] text-white"><div className="container-custom"><h2 className="text-center text-3xl font-black">Designed around how your organization works</h2><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{[[GraduationCap, "Schools", "SCHOOL"], [BriefcaseBusiness, "Corporate", "CORPORATE"], [Building2, "Institutions", "INSTITUTION"], [Trophy, "Events & General", "GENERAL"]].map(([Icon, title, audience]) => { const I = Icon as typeof Trophy; return <Link href={`/products?audience=${audience}`} key={title as string} className="rounded-2xl border border-white/15 p-6 hover:border-[var(--gold)]"><I className="text-[var(--gold)]" /><h3 className="mt-4 text-xl font-black">{title as string}</h3></Link>; })}</div></div></section>
    <section className="section-space bg-white"><div className="container-custom grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{[[BadgeCheck, "Manufacturing Focus", "Products built around the intended use."], [Palette, "Customization", "Colours, logos, printing and embroidery."], [PackageCheck, "Single or Bulk", "Order one piece or request volume support."], [ShieldCheck, "Quality Checks", "Specifications reviewed before dispatch."]].map(([Icon, title, text]) => { const I = Icon as typeof BadgeCheck; return <div key={title as string} className="content-card p-6"><I className="text-[var(--dark-gold)]" /><h3 className="mt-4 text-xl font-black text-[var(--dark-navy)]">{title as string}</h3><p className="mt-2 text-slate-600">{text as string}</p></div>; })}</div></section>
  </>;
}
