"use client";
import Link from "next/link";
import { Mail, MapPin, MessageCircle, Phone } from "lucide-react";
import { usePathname } from "next/navigation";
import BrandLogo from "./BrandLogo";
import DownloadCatalogueButton from "./DownloadCatalogueButton";
import type { PublicSiteAsset } from "@/types/site-assets";

type Props = { phone: string; whatsapp: string; email: string; address: string; description: string; logo: PublicSiteAsset | null; catalogue: PublicSiteAsset | null };
export default function Footer({ phone, whatsapp, email, address, description, logo, catalogue }: Props) { const pathname = usePathname(); if (pathname.startsWith("/admin")) return null; return <footer className="bg-[#041633] text-white"><div className="container-custom grid gap-10 py-14 md:grid-cols-2 lg:grid-cols-4"><div><BrandLogo logo={logo} /><p className="mt-5 leading-7 text-white/70">{description}</p></div><div><h2 className="footer-title">Products</h2><div className="footer-links"><Link href="/products?audience=SCHOOL">School Uniforms</Link><Link href="/products?audience=CORPORATE">Corporate Uniforms</Link><Link href="/products">Awards & Gifts</Link><DownloadCatalogueButton catalogue={catalogue} className="btn-gold mt-2" showMessage /></div></div><div><h2 className="footer-title">Company</h2><div className="footer-links"><Link href="/about">About</Link><Link href="/industries">Industries</Link><Link href="/bulk-orders">Bulk Orders</Link><Link href="/contact">Contact</Link></div></div><div><h2 className="footer-title">Contact</h2><div className="space-y-4 text-sm text-white/75"><a className="flex gap-3 hover:text-[var(--gold)]" href={`tel:+91${phone}`}><Phone size={18} />{phone}</a><a className="flex gap-3 break-all hover:text-[var(--gold)]" href={`mailto:${email}`}><Mail size={18} />{email}</a><p className="flex gap-3"><MapPin size={18} />{address}</p><a className="flex gap-3 hover:text-[var(--gold)]" href={`https://wa.me/${whatsapp}`} target="_blank" rel="noreferrer"><MessageCircle size={18} />WhatsApp</a></div></div></div><div className="border-t border-white/10 py-5 text-center text-sm text-white/55">© {new Date().getFullYear()} DS CREATIONS. All rights reserved.</div></footer>; }
