import Image from "next/image";
import AdminNotice from "@/components/admin/AdminNotice";
import { activateSiteAsset, deactivateSiteAsset, deleteSiteAsset, uploadSiteAsset } from "@/app/admin/actions";
import { getPrisma } from "@/lib/prisma";

export default async function AssetsPage({ searchParams }: { searchParams: Promise<{ type?: string; error?: string; saved?: string }> }) {
  const params = await searchParams; const type = params.type === "catalogue" ? "CATALOGUE" : "LOGO"; const assets = await getPrisma().siteAsset.findMany({ where: { type }, orderBy: { createdAt: "desc" } }); const isLogo = type === "LOGO";
  return <><p className="text-sm font-bold uppercase tracking-widest text-[var(--royal-blue)]">Assets</p><h1 className="mt-2 text-3xl font-black text-[var(--dark-navy)]">{isLogo ? "Logo & branding" : "Catalogue PDF"}</h1><p className="mt-3 text-slate-600">{isLogo ? "Upload JPG, PNG or WEBP files up to 5 MB. Use a tightly cropped transparent logo for best results." : "Upload PDF files up to 25 MB."}</p><div className="mt-6"><AdminNotice error={params.error} success={params.saved ? `${isLogo ? "Logo" : "Catalogue"} uploaded and activated.` : undefined} /></div>
    <form action={uploadSiteAsset} className="content-card grid gap-4 p-6 md:grid-cols-[1fr_1fr_auto]"><input type="hidden" name="type" value={type} /><label className="form-label">Title *<input name="title" required defaultValue={isLogo ? "DS CREATIONS logo" : "DS CREATIONS Product Catalogue"} className="form-control" /></label><label className="form-label">Choose file *<input name="file" type="file" required accept={isLogo ? "image/jpeg,image/png,image/webp" : "application/pdf"} className="form-control" /></label><button className="btn-gold self-end">Upload and activate</button></form>
    <div className="mt-8 grid gap-5 lg:grid-cols-2">{assets.map((asset) => <article className={`content-card p-6 ${asset.active ? "ring-2 ring-green-500" : ""}`} key={asset.id}>{isLogo ? <div className="relative h-44 overflow-hidden"><Image src={asset.url} alt={asset.title} fill className="object-contain object-left" sizes="(max-width: 1024px) 100vw, 50vw" /></div> : <a href={asset.url} target="_blank" rel="noopener noreferrer" className="flex h-44 items-center justify-center rounded-xl bg-red-50 text-xl font-black text-red-800">Open PDF</a>}<div className="mt-4 flex items-start justify-between gap-4"><div><h2 className="font-black text-[var(--dark-navy)]">{asset.title}</h2><p className="text-sm text-slate-500">{asset.active ? "Active on website" : "Inactive"} · {asset.createdAt.toLocaleDateString("en-IN")}</p></div><div className="flex flex-col gap-2">{asset.active ? <form action={deactivateSiteAsset}><input type="hidden" name="id" value={asset.id} /><input type="hidden" name="type" value={type} /><button className="text-sm font-bold text-amber-700">Deactivate</button></form> : <><form action={activateSiteAsset}><input type="hidden" name="id" value={asset.id} /><input type="hidden" name="type" value={type} /><button className="text-sm font-bold text-green-700">Activate</button></form><form action={deleteSiteAsset}><input type="hidden" name="id" value={asset.id} /><input type="hidden" name="type" value={type} /><button className="text-sm font-bold text-red-700">Delete</button></form></>}</div></div></article>)}</div>{!assets.length && <p className="mt-8 rounded-xl bg-white p-8 text-center text-slate-500">No {isLogo ? "logos" : "catalogues"} have been recorded yet.</p>}
  </>;
}
