import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Check, ChevronRight } from "lucide-react";
import { notFound } from "next/navigation";
import ProductActions from "@/components/ProductActions";
import ProductCard from "@/components/ProductCard";
import { getPublicProduct, getPublicProducts } from "@/lib/product-data";
import { effectivePrice, formatPrice, stockLabels } from "@/lib/format";

export const revalidate = 60;
export async function generateStaticParams() { return (await getPublicProducts()).map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const product = await getPublicProduct((await params).slug); if (!product) return { title: "Product Not Found" }; return { title: product.name, description: product.shortDescription, alternates: { canonical: `/products/${product.slug}` }, openGraph: { title: `${product.name} | DS CREATIONS`, description: product.shortDescription, url: `/products/${product.slug}`, images: [product.mainImage] } }; }

export default async function ProductPage({ params }: { params: Promise<{ slug: string }> }) {
  const slug = (await params).slug; const [product, allProducts] = await Promise.all([getPublicProduct(slug), getPublicProducts()]); if (!product) notFound();
  const related = allProducts.filter((item) => item.category === product.category && item.id !== product.id).slice(0, 4); const discount = product.price && product.offerPrice ? Math.round((1 - product.offerPrice / product.price) * 100) : 0;
  return <>
    <section className="bg-[var(--light-bg)] py-5"><nav aria-label="Breadcrumb" className="container-custom flex flex-wrap items-center gap-2 text-sm text-slate-600"><Link href="/">Home</Link><ChevronRight size={14} /><Link href="/products">Products</Link><ChevronRight size={14} /><span className="text-[var(--dark-navy)]">{product.name}</span></nav></section>
    <section className="section-space bg-white"><div className="container-custom grid gap-12 lg:grid-cols-2"><div><div className="relative aspect-[4/3] overflow-hidden rounded-3xl bg-[var(--light-bg)]"><Image src={product.mainImage} alt={product.name} fill priority unoptimized={product.mainImage.startsWith("http")} className="object-cover" sizes="(max-width: 1024px) 100vw, 50vw" /></div><div className="mt-4 grid grid-cols-3 gap-3">{product.galleryImages.map((image, index) => <div className="relative aspect-[4/3] overflow-hidden rounded-xl border border-slate-200" key={`${image}-${index}`}><Image src={image} alt={`${product.name} view ${index + 1}`} fill unoptimized={image.startsWith("http")} className="object-cover" sizes="180px" /></div>)}</div></div>
      <div><p className="font-black uppercase tracking-widest text-[var(--royal-blue)]">{product.category} · {product.subcategory}</p><h1 className="mt-3 text-4xl font-black text-[var(--dark-navy)]">{product.name}</h1><p className="mt-3 text-sm text-slate-500">SKU: {product.sku} · Audience: {product.audience}</p><p className="mt-5 leading-8 text-slate-600">{product.description}</p><div className="mt-6 rounded-2xl bg-[var(--soft-gold)] p-5"><div className="flex flex-wrap items-end gap-3">{product.price === null ? <strong className="text-2xl text-[var(--dark-navy)]">Contact for price</strong> : <><strong className="text-3xl text-[var(--dark-navy)]">{formatPrice(effectivePrice(product))}</strong>{product.offerPrice && <del className="text-lg text-slate-500">{formatPrice(product.price)}</del>}{discount > 0 && <span className="rounded-full bg-[var(--gold)] px-3 py-1 text-sm font-black">Save {discount}%</span>}</>}</div><p className="mt-2 text-sm text-slate-600">GST {product.gstPercentage}% estimated separately · Minimum order: {product.minimumOrderQuantity} piece · {stockLabels[product.stockStatus]}</p></div><ProductActions product={product} /></div></div></section>
    <section className="section-space bg-[var(--light-bg)]"><div className="container-custom grid gap-8 lg:grid-cols-3"><div className="content-card p-7 lg:col-span-2"><h2 className="text-2xl font-black text-[var(--dark-navy)]">Features & specifications</h2><ul className="mt-5 grid gap-3 sm:grid-cols-2">{product.features.map((feature) => <li key={feature} className="flex gap-3"><Check className="shrink-0 text-[var(--dark-gold)]" size={20} />{feature}</li>)}</ul><dl className="mt-7 divide-y divide-slate-100">{Object.entries(product.specifications).map(([key, value]) => <div className="grid grid-cols-2 gap-4 py-3" key={key}><dt className="font-bold text-slate-600">{key}</dt><dd>{value}</dd></div>)}</dl></div><div className="content-card p-7"><h2 className="text-xl font-black text-[var(--dark-navy)]">Customization</h2><dl className="mt-5 space-y-3 text-sm"><div className="flex justify-between"><dt>Customization</dt><dd className="font-bold">{product.customizationAvailable ? "Available" : "Standard"}</dd></div><div className="flex justify-between"><dt>Printing</dt><dd className="font-bold">{product.printingAvailable ? "Available" : "Not applicable"}</dd></div><div className="flex justify-between"><dt>Embroidery</dt><dd className="font-bold">{product.embroideryAvailable ? "Available" : "Not applicable"}</dd></div><div className="flex justify-between"><dt>Material</dt><dd className="text-right font-bold">{product.material}</dd></div><div className="flex justify-between gap-4"><dt>Delivery</dt><dd className="max-w-56 text-right">{product.deliveryTime}</dd></div></dl></div></div></section>
    {related.length > 0 && <section className="section-space bg-white"><div className="container-custom"><h2 className="text-3xl font-black text-[var(--dark-navy)]">Related products</h2><div className="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{related.map((item) => <ProductCard product={item} key={item.id} />)}</div><Link href="/products" className="btn-secondary mt-8 inline-flex">← Back to products</Link></div></section>}
  </>;
}
